export const IMG_CDN_LINK =
  'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

export const restaurantList = [
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '358377',
        name: 'The Cake Zone',
        uuid: '40e5106a-eed4-4558-b22e-fe49c04f6ae6',
        city: '1',
        area: 'Bommanahalli',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'ezyi8ps5eid5emamyizm',
        cuisines: ['Bakery'],
        tags: [],
        costForTwo: 12000,
        costForTwoString: '₹120 FOR TWO',
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: '23 MINS',
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: 'the-cake-zone-hsr-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'THE CAKE ZONE, 3rd Cross Road, Bandepalya, Muneshwara Nagar, Bengaluru, Karnataka, India',
        locality: 'Garvebhavi Palya',
        parentId: 206335,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.7 kms',
        hasSurge: false,
        sla: {
          restaurantId: '358377',
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.2',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '365010',
        name: 'Hotel Salam',
        uuid: '0a29b957-8817-4d4c-bc32-ca009921472d',
        city: '1',
        area: 'Bommanahalli',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'hgdmw8uwgewhiewwovjh',
        cuisines: ['Biryani', 'Tandoor', 'Arabian', 'Indian', 'Beverages'],
        tags: [],
        costForTwo: 25000,
        costForTwoString: '₹250 FOR TWO',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: '27 MINS',
        lastMileTravel: 3.5,
        slugs: {
          restaurant: 'hotel-salam-hsr-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '43/1,OPP.Salarpuria Serenity ,M G Palya Main Road, Bangalore-560068',
        locality: 'M G Palya',
        parentId: 101873,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '3.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '365010',
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 3.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.9',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '167636',
        name: 'Easy Bites by Hotel Empire',
        uuid: 'd76f8e3b-d8f1-4254-b6f5-636934914441',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'd06b7fa84cb8f8193f60d4c2de172347',
        cuisines: ['Snacks', 'Fast Food', 'Beverages'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: '38 MINS',
        lastMileTravel: 4.699999809265137,
        slugs: {
          restaurant: 'easy-bites-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'Bommanahalli, 169/A/170, 9th Main Rd, Sector 6, HSR Layout, Bengaluru, Karnataka 560102',
        locality: '6th Sector',
        parentId: 8503,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [
          {
            type: 'PROMOTED',
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5629199~p=28~eid=00000185-9630-e292-1c47-8839006c1c29',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.6 kms',
        hasSurge: false,
        sla: {
          restaurantId: '167636',
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 4.699999809265137,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.1',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '69903',
        name: 'Third Wave Coffee',
        uuid: 'b0a453d5-ea1a-499d-b379-3ea55a17888f',
        city: '1',
        area: '7th Sector',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'c366bd390008601fb707936ede9b1b78',
        cuisines: ['Beverages', 'Bakery', 'Continental'],
        tags: [],
        costForTwo: 40000,
        costForTwoString: '₹400 FOR TWO',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: '28 MINS',
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: 'third-wave-coffee-roasters-hsr-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '249, 14th Main Rd, Sector 7, HSR Layout, Bengaluru, Karnataka 560102',
        locality: '7th Sector',
        parentId: 274773,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '40% off',
          shortDescriptionList: [
            {
              meta: '40% off | Use GUILTFREEJAN',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '40% off up to ₹100 | Use code GUILTFREEJAN',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '40% OFF',
          shortDescriptionList: [
            {
              meta: 'Use GUILTFREEJAN',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '40% off up to ₹100 | Use code GUILTFREEJAN',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [
          {
            type: 'PROMOTED',
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5618812~p=31~eid=00000185-9630-e292-1c47-883a006c1f46',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '3.9 kms',
        hasSurge: false,
        sla: {
          restaurantId: '69903',
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.3',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '56589',
        name: 'Roti Wala',
        uuid: '257a0889-b243-4252-b84a-6c9f1760d58f',
        city: '1',
        area: 'Btm Layout',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'ptetuqkrhmpd8tiqiztg',
        cuisines: [
          'North Indian',
          'Home Food',
          'Thalis',
          'Chinese',
          'Punjabi',
          'South Indian',
          'Ice Cream',
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 46,
        minDeliveryTime: 45,
        maxDeliveryTime: 55,
        slaString: '45-55 MINS',
        lastMileTravel: 7.199999809265137,
        slugs: {
          restaurant: 'roti-wala-lavelle-road-central-bangalore',
          city: 'bangalore',
        },
        cityState: '1',
        address: '#239, 7TH Cross, Btm Stage 2. NS Palya, 560076',
        locality: '2nd Stage',
        parentId: 171678,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '7.1 kms',
        hasSurge: false,
        sla: {
          restaurantId: '56589',
          deliveryTime: 46,
          minDeliveryTime: 45,
          maxDeliveryTime: 55,
          lastMileTravel: 7.199999809265137,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.2',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '154991',
        name: 'Cakewala',
        uuid: '0dbff6cf-7ed8-4779-bf8a-065867e787cb',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'n10rf2spdqlvzqbafk5y',
        cuisines: ['Desserts'],
        tags: [],
        costForTwo: 40000,
        costForTwoString: '₹400 FOR TWO',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: '29 MINS',
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: 'cakewala-hsr-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'ORIENTAL TOWERS, NO. 461, 4TH SECTOR, 17TH CROSS, HSR LAYOUT, BANGALORE - 560 102',
        locality: '4th Sector',
        parentId: 3492,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.3 kms',
        hasSurge: false,
        sla: {
          restaurantId: '154991',
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.4',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '241027',
        name: 'Namaste',
        uuid: '2f63dd57-5d9e-4e38-84aa-21c5b7229b86',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'dtcwa1rxdskp3crqvpr3',
        cuisines: [
          'South Indian',
          'Thalis',
          'Biryani',
          'Desserts',
          'Beverages',
          'Indian',
        ],
        tags: [],
        costForTwo: 10000,
        costForTwoString: '₹100 FOR TWO',
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: '33 MINS',
        lastMileTravel: 5.5,
        slugs: {
          restaurant: 'namaste-hsr-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '1086/A, 1087/A, 14th Main, 18th Cross Rd, near BDA Complex, III Sector, HSR Layout, Bengaluru, Karnataka 560102',
        locality: '3rd Sector',
        parentId: 366271,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '5.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '241027',
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 5.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '336830',
        name: 'Onesta',
        uuid: '0fe6a19f-e7ca-4b77-803c-54b5f1c3b5e7',
        city: '1',
        area: 'Bommanahalli',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'ib0niiepzannkvo0ffbp',
        cuisines: ['Italian', 'Desserts', 'Pizzas', 'American', 'Snacks'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: '38 MINS',
        lastMileTravel: 4.199999809265137,
        slugs: {
          restaurant: 'onesta-8-bommanhalli-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address: 'No#1 . 2nd main Rajiv Gandhi Nagar,Bommanhalli bangakore',
        locality: 'Gandi Nagar',
        parentId: 11785,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.1 kms',
        hasSurge: false,
        sla: {
          restaurantId: '336830',
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 4.199999809265137,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.9',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '374909',
        name: 'Thalassery Restaurant',
        uuid: '118ee8b3-e02f-4189-b492-d2ac4229fd6b',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'fc4kehquqhqbvctqscaq',
        cuisines: ['Indian', 'Chinese', 'Desserts', 'Beverages'],
        tags: [],
        costForTwo: 40000,
        costForTwoString: '₹400 FOR TWO',
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: '33 MINS',
        lastMileTravel: 4,
        slugs: {
          restaurant: 'thalassery-restaurant-hsr-hsr-3',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '#36, RELIABLE RESIDENCY, HARLUR MAIN ROAD, HSR LAYOUT POST, NEAR INDIAN OIL PETROL BUNK',
        locality: 'Harlur Main Road',
        parentId: 14391,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4 kms',
        hasSurge: false,
        sla: {
          restaurantId: '374909',
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 4,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '6404',
        name: 'Kabab Magic',
        uuid: 'd537d357-6f6d-444f-96b5-9a9ec33206f9',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'f7xqgju9oce3l5a91zgd',
        cuisines: ['North Indian', 'Chinese', 'Biryani', 'Tandoor'],
        tags: [],
        costForTwo: 30000,
        costForTwoString: '₹300 FOR TWO',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: '35 MINS',
        lastMileTravel: 5.800000190734863,
        slugs: {
          restaurant: 'kabab-magic-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'No:1565, Masti Square, Outer Ring Road, Sector 1, Agram, Agara Village, 1st Sector, HSR Layout, Bengaluru',
        locality: '1st sector',
        parentId: 527,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '5.8 kms',
        hasSurge: false,
        sla: {
          restaurantId: '6404',
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 5.800000190734863,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '590119',
        name: 'Bakingo',
        uuid: '728a87a4-eaaf-45d1-a3af-b685bd6e86ab',
        city: '1',
        area: 'BTM Layout',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'ctjaedvif65wepxpjwwk',
        cuisines: ['Bakery', 'Desserts', 'Beverages', 'Snacks'],
        tags: [],
        costForTwo: 29900,
        costForTwoString: '₹299 FOR TWO',
        deliveryTime: 39,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        slaString: '35-45 MINS',
        lastMileTravel: 6.800000190734863,
        slugs: {
          restaurant: 'bakingo-btm-layout-kadugodi',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '75,16th Main Road 9th Cross 1st Stage BTM Layout, Bangalore , Karnataka - 560004',
        locality: '1st  Stage',
        parentId: 3818,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '6.8 kms',
        hasSurge: false,
        sla: {
          restaurantId: '590119',
          deliveryTime: 39,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          lastMileTravel: 6.800000190734863,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.1',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '206526',
        name: 'Kalingas',
        uuid: 'f89a3f57-78e9-459f-8c6c-a14d1d70198a',
        city: '1',
        area: 'BTM Layout',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'tw8oa22piypiun4ildq4',
        cuisines: ['North Indian', 'Oriya'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 43,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        slaString: '40-50 MINS',
        lastMileTravel: 7.199999809265137,
        slugs: {
          restaurant: 'kalingas-btm-btm',
          city: 'bangalore',
        },
        cityState: '1',
        address: '399,16th Main, 2nd Stage, BTM Layout,Bangalore-560076',
        locality: '2nd Stage',
        parentId: 16766,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '7.1 kms',
        hasSurge: false,
        sla: {
          restaurantId: '206526',
          deliveryTime: 43,
          minDeliveryTime: 40,
          maxDeliveryTime: 50,
          lastMileTravel: 7.199999809265137,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.2',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '8174',
        name: 'Corner House Ice Cream',
        uuid: '7621d545-981c-4ac0-802a-f431844ec87b',
        city: '1',
        area: 'HSR Layout',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'vaztnu7dffyzzcd9fka6',
        cuisines: ['Ice Cream', 'Desserts'],
        tags: [],
        costForTwo: 25000,
        costForTwoString: '₹250 FOR TWO',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: '28 MINS',
        lastMileTravel: 4.400000095367432,
        slugs: {
          restaurant: 'corner-house-ice-cream-sector-7-hsr',
          city: 'bangalore',
        },
        cityState: '1',
        address: '1001, 9th Main, Sector 7, HSRLayout, Bangalore',
        locality: '7th Sector',
        parentId: 65254,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.4 kms',
        hasSurge: false,
        sla: {
          restaurantId: '8174',
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 4.400000095367432,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.7',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '383072',
        name: 'Rampyari Chaiwala Netaji Bhajiawala',
        uuid: '05c721df-ebc3-44ae-92af-cc637cf5fa37',
        city: '1',
        area: 'BTM Layout',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'l8qhaivflraozfaf2abu',
        cuisines: ['Indian', 'Snacks'],
        tags: [],
        costForTwo: 10000,
        costForTwoString: '₹100 FOR TWO',
        deliveryTime: 41,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        slaString: '40-50 MINS',
        lastMileTravel: 6.300000190734863,
        slugs: {
          restaurant: 'rampyari-chaiwala-netaji-bhajiawala-btm-btm',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          '08, rampyari chaiwala Netaji bhajiawala, mchs colony, opposite to lake,btm 2nd stage , bangalore 560076',
        locality: '2nd Stage',
        parentId: 166698,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '6.3 kms',
        hasSurge: false,
        sla: {
          restaurantId: '383072',
          deliveryTime: 41,
          minDeliveryTime: 40,
          maxDeliveryTime: 50,
          lastMileTravel: 6.300000190734863,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '211192',
        name: "La Pino'z Pizza",
        uuid: 'ebf80a67-354e-445f-90c8-e078823363cd',
        city: '1',
        area: 'BTM Layout',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'lczhp9lptdzbqn09nfns',
        cuisines: ['Pizzas', 'Italian', 'Snacks', 'Continental', 'Desserts'],
        tags: [],
        costForTwo: 25000,
        costForTwoString: '₹250 FOR TWO',
        deliveryTime: 43,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        slaString: '40-50 MINS',
        lastMileTravel: 6.5,
        slugs: {
          restaurant: "la-pino'z-pizza-btm-btm",
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'SILVER BIJOUX, Opp to Pizza Hut, Sunshine Colony, BTM 2nd Stage, Bengaluru, Karnataka, India',
        locality: '2nd Stage',
        parentId: 4961,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '6.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '211192',
          deliveryTime: 43,
          minDeliveryTime: 40,
          maxDeliveryTime: 50,
          lastMileTravel: 6.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.9',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '601621',
        name: 'Kanti Sweets',
        uuid: '7a201dab-2527-41e3-8b96-80b85bdccb1b',
        city: '1',
        area: 'Bommanahalli',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'bpje3y8wovndkts25tpo',
        cuisines: ['Sweets'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 27,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        slaString: '25-35 MINS',
        lastMileTravel: 3,
        slugs: {
          restaurant: 'kanti-sweets-btm-btm-5',
          city: 'bangalore',
        },
        cityState: '1',
        address:
          'Kanti Sweets Ground Floor, Hongasandra, Begur Main Road and Industrial Area, Bangalore south Taluk, Bangalore - 560068',
        locality: 'Hongasandra',
        parentId: 4700,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹90 | Use code WELCOME50',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '3 kms',
        hasSurge: false,
        sla: {
          restaurantId: '601621',
          deliveryTime: 27,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.5',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
];
